version: v1
name: wf-customers-profile
type: workflow
tags:
  - demo.customers
workflow:
  title: Connect customers
  dag:
  - name: customers-profile-profile
    title: customers profile Profiler
    description: The job performs profiling on the customers data
    spec:
      stack: flare:3.0
      compute: runnable-default
      tier: system
      title: customers Profiler
      persistentVolume:
        name: persistent-v
        directory: fides
      flare:
        driver:
          coreLimit: 1100m
          cores: 1
          memory: 1048m
        executor:
          coreLimit: 1200m
          cores: 1
          instances: 1
          memory: 1000m 
        job:
          explain: true
          inputs:
            - name: customers
              dataset:  dataos://icebasedev:retail_accelerator/customers
              format: iceberg
          logLevel: INFO
          profile:
            level: basic
