version: v1
name: wf-product
type: workflow
tags:
  - demo.product
description: The job ingests retail product data from Blob Storage to icebase
workflow:
  title: Connect retail product
  dag:
    - name: retail-product
      title: retail-product Dataset
      spec:
        tags:
          - demo.product
        stack: flare:3.0
        compute: runnable-default
        flare:
          driver:
            coreLimit: 1100m
            cores: 1
            memory: 1048m
          executor:
            coreLimit: 1200m
            cores: 1
            instances: 1
            memory: 1000m 
          job:
            explain: true
            inputs:
              - name: product
                dataset: dataos://thirdparty01:analytics/retail_accelerator/product/product.csv?acl=rw                       
                format: csv
            logLevel: INFO
            outputs:
              - name: final
                dataset: dataos://icebase:retail_accelerator/product?acl=rw
                format: Iceberg
                description: This dataset gives you details of all retail products and its corresponding attributes.
                tags:
                  - demo.product
                options:
                  saveMode: overwrite
                  iceberg:
                    properties:
                      write.format.default: parquet
                      write.metadata.compression-codec: gzip
                title: retail product Source Data
            steps:
              - sequence:
                  - name: final
                    sql: select * from product
                    functions:
                       - name: any_timestamp
                         column: launched_ts
                         asColumn: launched_ts
                       - name: set_type
                         columns:
                          list_price: float
                          cost_price: float
                          sale_price: float

                                             
    - name: dt-retail-product
      spec:
        stack: toolbox
        compute: runnable-default
        toolbox:
          dataset: dataos://icebase:retail_accelerator/product?acl=rw
          action:
            name: set_version
            value: latest
      dependencies:
        - retail-product